language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
virtualenv:
  system_site_packages: true
install:
  - pip install -r requirements.txt
deploy:
  provider: pypi
